# working test: print 'Welcome to Advent of Code 2024'
# alternativ in bash: curl -k GET https://selforg.mac/aoc24/welcome
GET https://selforg.mac/aoc24/welcome
###

# Day 1 test / my solution 11
GET https://selforg.mac/aoc24/day1/a/test
###

# Day 1 part a / my solution 3246517
GET https://selforg.mac/aoc24/day1/a/live
###

# day 1 part b / my solution 29379307
GET https://selforg.mac/aoc24/day1/b/live
###



# Day 2 test / my solution 2
GET https://selforg.mac/aoc24/day2/a/test
###

# Day 2 part a / my solution 670
GET https://selforg.mac/aoc24/day2/a/live
###

# day 2 part b / my solution 700
GET https://selforg.mac/aoc24/day2/b/live
###



# Day 3 test / my solution 161
GET https://selforg.mac/aoc24/day3/a/test
###

# Day 3 part a / my solution 161289189
GET https://selforg.mac/aoc24/day3/a/live
###

# day 3 part b / my solution 83595109
GET https://selforg.mac/aoc24/day3/b/live
###



# Day 4 test / my solution 18
GET https://selforg.mac/aoc24/day4/a/test
###

# Day 4 part a / my solution 2532
GET https://selforg.mac/aoc24/day4/a/live
###

# day 4 part b / my solution 1941
GET https://selforg.mac/aoc24/day4/b/live
###



# Day 5 test / my solution 143
GET https://selforg.mac/aoc24/day5/a/test
###

# Day 5 part a / my solution 4790
GET https://selforg.mac/aoc24/day5/a/live
###

# day 5 part b / my solution (unsolved)
#GET https://selforg.mac/aoc24/day5/b/live
###



# Day 6 test / my solution 44
GET https://selforg.mac/aoc24/day6/a/test
###

# Day 6 part a / my solution
GET https://selforg.mac/aoc24/day6/a/live
###

