# working test: print 'Welcome to Advent of Code 2024'
# alternativ in bash: curl -k GET https://selforg.mac/aoc24/welcome
GET https://selforg.mac/aoc24/welcome
###

# Day 1 test
GET https://selforg.mac/aoc24/day1/a/test
###

# Day 1 live
GET https://selforg.mac/aoc24/day1/a/live
###

# Day 2 test
GET https://selforg.mac/aoc24/day2/a/test
###

# Day 2 live
GET https://selforg.mac/aoc24/day2/a/live
###

